package com.example.ui.settings

object Localization {
    fun get(key: String, language: String): String {
        val strings = translations[language] ?: translations["English"] ?: emptyMap()
        return strings[key] ?: translations["English"]?.get(key) ?: key
    }

    private val translations = mapOf(
        "English" to mapOf(
            "app_title" to "Math Expressive",
            "subtitle" to "Tingkatan 2 Mathematics Made Visual",
            "search_lang" to "Search language...",
            "app_lang" to "Application language",
            "appearance" to "Appearance",
            "theme_sec" to "THEME",
            "enable_dynamic" to "Enable dynamic theme",
            "dark_theme" to "Dark theme",
            "disable_blurs" to "Disable blur effects",
            "disable_blurs_desc" to "Disable blur effects throughout the app",
            "use_sys_font" to "Use system font",
            "use_sys_font_desc" to "Use the device font instead of the app font",
            "off" to "Off",
            "on" to "On",
            "search_placeholder" to "Search language...",
            "solved_subject" to "Solved for subject:",
            "steps_title" to "Transformation Steps",
            "select_subject" to "Choose variable to isolate (subject):",
            "back" to "Back",
            "welcome" to "Select a Mathematics Topic",
            "topic_patterns" to "Pola dan Jujukan (Patterns & Sequences)",
            "topic_algebra" to "Ungkapan & Rumus Algebra (Algebraic Formulae)",
            "topic_polygons" to "Poligon (Polygons)",
            "topic_circles" to "Bulatan (Circles)",
            "topic_shapes" to "Bentuk Tiga Dimensi (3D Shapes)",
            "solve" to "Solve",
            "calculate" to "Calculate",
            "result" to "Result",
            "explanation" to "Explanation",
            "hcf_lcm" to "Determine HCF (FSTB) & LCM (GSTK)",
            "expansion" to "Expansion (Kembangan)",
            "factorisation" to "Factorisation (Pemfaktoran)",
            "subject_title" to "Change Subject of Formula",
            "pola_desc" to "Analyze number sequences, find the pattern, and write down the n-th term general formula easily.",
            "formulae_desc" to "Change the subject of a formula step-by-step, expand products of expressions, or factorise quadratic terms.",
            "polygons_desc" to "Explore interior and exterior angles of regular polygons and calculate sum of angles with diagrams.",
            "circles_desc" to "Calculate chord lengths, circumference, area, arc length and sector area with a visual circle diagram.",
            "shapes_desc" to "Calculate total surface area and volume of 3D shapes (cylinders, cones, spheres) and explore their flat net patterns.",
            "enter_seq" to "Enter number sequence, separated by commas (e.g. 5, 12, 19, 26):",
            "pattern_is" to "Pattern identified:",
            "general_term" to "General term formula:",
            "seq_error" to "Please enter at least 3 valid numbers separated by commas.",
            "factor_title" to "Quadratic Factorisation",
            "factor_desc" to "Factorise ax² + bx + c using cross multiplication (pendaraban silang)",
            "expand_title" to "Expansion Solver",
            "expand_desc" to "Expand (ax + b)(cx + d) step-by-step",
            "hcf_title" to "HCF & LCM Solver",
            "hcf_desc" to "Using repeated division method (pembahagian berulang)",
            "num_list_prompt" to "Enter positive integers separated by commas (e.g. 12, 18, 30):",
            "divide_step" to "Divide by",
            "polygon_sides" to "Number of sides (polygon n-sided):",
            "interior_sum" to "Sum of Interior Angles:",
            "each_interior" to "Each Interior Angle:",
            "each_exterior" to "Each Exterior Angle:",
            "polygon_math_step1" to "Sum of interior angles = (n ÷ 2) × 180° in general, or correctly written as (n - 2) × 180°",
            "circle_radius" to "Circle radius (r):",
            "circle_angle" to "Subtended angle at center (θ°):",
            "circumference" to "Circumference (2 × π × r):",
            "circle_area" to "Circle Area (π × r²):",
            "arc_length" to "Arc Length (θ/360 × 2 × π × r):",
            "sector_area" to "Sector Area (θ/360 × π × r²):",
            "shape_type" to "Select 3D Shape:",
            "volume" to "Volume",
            "surface_area" to "Surface Area",
            "nets_visualizer" to "Nets Visualizer",
            "prism" to "Triangular Prism",
            "pyramid" to "Square Pyramid",
            "cylinder" to "Cylinder",
            "cone" to "Cone",
            "sphere" to "Sphere",
            "h_val" to "Height (h):",
            "r_val" to "Radius (r):",
            "w_val" to "Width (w):",
            "l_val" to "Length (l):",
            "s_val" to "Slant height (s):",
            "student_tip" to "Student Tip: Remember that in school textbooks and formula sheets, a fraction line represents division (÷), and side-by-side variables like 'ab' mean 'a multiplied by b' (a × b).",
            "swipe_to_see" to "Swipe the carousel below to see how each step moves components across the equals (=) sign!"
        ),
        "Bahasa Melayu" to mapOf(
            "app_title" to "Math Expressive",
            "subtitle" to "Matematik Tingkatan 2 Secara Visual",
            "search_lang" to "Cari bahasa...",
            "app_lang" to "Bahasa aplikasi",
            "appearance" to "Rupa Paras",
            "theme_sec" to "TEMA",
            "enable_dynamic" to "Dayakan tema dinamik",
            "dark_theme" to "Tema gelap",
            "disable_blurs" to "Nyahdayakan kesan kabur",
            "disable_blurs_desc" to "Nyahdayakan kesan kabur di seluruh aplikasi",
            "use_sys_font" to "Guna fon sistem",
            "use_sys_font_desc" to "Guna fon peranti berbanding fon aplikasi",
            "off" to "Tutup",
            "on" to "Buka",
            "search_placeholder" to "Cari bahasa...",
            "solved_subject" to "Selesai untuk subjek:",
            "steps_title" to "Langkah-Langkah Transformasi",
            "select_subject" to "Pilih pemboleh ubah untuk diasingkan (subjek):",
            "back" to "Kembali",
            "welcome" to "Pilih Tajuk Matematik",
            "topic_patterns" to "Pola dan Jujukan",
            "topic_algebra" to "Ungkapan & Rumus Algebra",
            "topic_polygons" to "Poligon",
            "topic_circles" to "Bulatan",
            "topic_shapes" to "Bentuk Tiga Dimensi (3D)",
            "solve" to "Selesaikan",
            "calculate" to "Kira",
            "result" to "Keputusan",
            "explanation" to "Penerangan",
            "hcf_lcm" to "Cari FSTB & GSTK",
            "expansion" to "Kembangan",
            "factorisation" to "Pemfaktoran",
            "subject_title" to "Tukar Perkara Rumus (Subject)",
            "pola_desc" to "Analisis jujukan nombor, cari pola, dan tulis rumus sebutan ke-n (general term) dengan mudah.",
            "formulae_desc" to "Tukar perkara rumus langkah demi langkah, kembangkan hasil darab ungkapan, atau faktorkan sebutan kuadratik.",
            "polygons_desc" to "Terokai sudut pedalaman dan peluaran poligon sekata serta kira hasil tambah sudut dengan rajah interaktif.",
            "circles_desc" to "Kira panjang perentas, lilitan, luas, panjang lengkok, dan luas sektor berserta gambar rajah bulatan.",
            "shapes_desc" to "Kira jumlah luas permukaan dan isipadu bentuk 3D (silinder, kon, sfera) serta lihat bentangan (nets).",
            "enter_seq" to "Masukkan jujukan nombor, dipisahkan oleh koma (contoh: 5, 12, 19, 26):",
            "pattern_is" to "Pola yang dikesan:",
            "general_term" to "Rumus sebutan ke-n (Tn):",
            "seq_error" to "Sila masukkan sekurang-kurangnya 3 nombor sah yang dipisahkan oleh koma.",
            "factor_title" to "Pemfaktoran Kuadratik",
            "factor_desc" to "Faktorkan ax² + bx + c menerusi kaedah pendaraban silang",
            "expand_title" to "Penyelesai Kembangan",
            "expand_desc" to "Kembangkan (ax + b)(cx + d) langkah demi langkah",
            "hcf_title" to "Penyelesai FSTB & GSTK",
            "hcf_desc" to "Menggunakan kaedah pembahagian berulang",
            "num_list_prompt" to "Masukkan integer positif dipisahkan dengan koma (contoh: 12, 18, 30):",
            "divide_step" to "Bahagi dengan",
            "polygon_sides" to "Bilangan sisi (nilai n):",
            "interior_sum" to "Hasil Tambah Sudut Pedalaman:",
            "each_interior" to "Setiap Sudut Pedalaman:",
            "each_exterior" to "Setiap Sudut Peluaran:",
            "polygon_math_step1" to "Hasil tambah sudut pedalaman = (n - 2) × 180°",
            "circle_radius" to "Jejari bulatan (j):",
            "circle_angle" to "Sudut tercakup pada pusat (θ°):",
            "circumference" to "Lilitan Bulatan (2 × π × j):",
            "circle_area" to "Luas Bulatan (π × j²):",
            "arc_length" to "Panjang Lengkok (θ/360 × 2 × π × j):",
            "sector_area" to "Luas Sektor (θ/360 × π × j²):",
            "shape_type" to "Pilih Bentuk 3D:",
            "volume" to "Isipadu",
            "surface_area" to "Luas Permukaan",
            "nets_visualizer" to "Visual Bentangan (Net)",
            "prism" to "Prisma Segi Tiga",
            "pyramid" to "Piramid Tapak Segi Empat",
            "cylinder" to "Silinder",
            "cone" to "Kon",
            "sphere" to "Sfera",
            "h_val" to "Tinggi (t):",
            "r_val" to "Jejari (j):",
            "w_val" to "Lebar (l):",
            "l_val" to "Panjang (p):",
            "s_val" to "Tinggi serong (s):",
            "student_tip" to "Tip Pelajar: Ingat bahawa dalam buku teks sekolah, garisan pecahan bermaksud bahagi (÷), dan pemboleh ubah bersebelahan seperti 'ab' bermaksud 'a didarab dengan b' (a × b).",
            "swipe_to_see" to "Leret karusel di bawah untuk melihat bagaimana setiap langkah memindahkan komponen merentasi tanda sama dengan (=)!"
        )
    )
}
